version: "3"

services:
  icp-onchain:
    container_name: icp-onchain
    build:
      context: .
      dockerfile: ./servers/icp-onchain/prod.Dockerfile
      args:
        PROJECT: icp-onchain
        TURBO_TEAM: $TURBO_TEAM
        TURBO_TOKEN: $TURBO_TOKEN
      tags:
        - ghcr.io/cyberninjaslab/icp-node-backend/icp-onchain
    restart: always
    ports:
      - 3001:3001
    networks:
      - app_network
    stop_grace_period: 1s

networks:
  app_network:
