version: "3"

services:
  core:
    container_name: core
    build:
      context: .
      dockerfile: ./services/core/prod.Dockerfile
      args:
        PROJECT: "@icptokens/core"
        PROJECT_FOLDER: core
        TURBO_TEAM: $TURBO_TEAM
        TURBO_TOKEN: $TURBO_TOKEN
      tags:
        - ghcr.io/cyberninjaslab/icp-tokens-node/core
    restart: always
    ports:
      - 3000:3000
    networks:
      - app_network
    stop_grace_period: 1s

networks:
  app_network:
